### ISSUE TITLE
how TO KNOW NOT VIRUS

### ISSUE THREAD

**Issue by qizq1337** [Ethone-SB/Ethone-Selfbot#2]
OMG WAT IF THSI IS VIREZ CZU EXE
![image](https://user-images.githubusercontent.com/95669102/148130206-ebd7a05a-6656-4ced-960d-2984a6243151.png)
![image](https://user-images.githubusercontent.com/95669102/148130210-72b976d5-ea6b-4b21-a1e6-fa9ae291af7e.png)
![image](https://user-images.githubusercontent.com/95669102/148130212-4aab1bbd-99b8-4d75-bebd-d1def52f0aa6.png)
![image](https://user-images.githubusercontent.com/95669102/148130213-91d84307-8dd3-4f4b-9cd2-1234db25e1a4.png)
![image](https://user-images.githubusercontent.com/95669102/148130215-5023e6ab-d1aa-4bba-ac6c-abf076f537ad.png)
![image](https://user-images.githubusercontent.com/95669102/148130216-54bb6241-7ad4-4166-a181-9534962f9249.png)
![image](https://user-images.githubusercontent.com/95669102/148130221-96cadc4a-b17b-40a0-b290-d8f919e2a2b0.png)

**Comment by qizq1337** [comment]
![image](https://user-images.githubusercontent.com/95669102/148130306-34378d7d-9ae8-494a-b52c-020911b493cc.png)

**Comment by qizq1337** [comment]
![image](https://user-images.githubusercontent.com/95669102/148130332-75a6d09d-d24b-47dc-9a9c-2e4a0287afd6.png)

**Comment by Lodisus** [comment]
retard

**Comment by Lodisus** [comment]
scan on virustotal btw
